// GENERATED by scripts/validate-packs.ts — do not edit. Run `npm run validate`.
//
// Metro only bundles files reached by a literal require(), so every pack
// and image the app ships is listed here.

import type { BundledRegistry } from "./BundledPackSource";

export const bundledRegistry: BundledRegistry = {
  "solar-system": {
    pack: require("../../packs/solar-system/pack.json"),
    media: {
      "images/cover.webp": require("../../packs/solar-system/images/cover.webp"),
      "images/cover.thumb.webp": require("../../packs/solar-system/images/cover.thumb.webp"),
      "images/sun.webp": require("../../packs/solar-system/images/sun.webp"),
      "images/sun.thumb.webp": require("../../packs/solar-system/images/sun.thumb.webp"),
      "images/mercury.webp": require("../../packs/solar-system/images/mercury.webp"),
      "images/mercury.thumb.webp": require("../../packs/solar-system/images/mercury.thumb.webp"),
      "images/venus.webp": require("../../packs/solar-system/images/venus.webp"),
      "images/venus.thumb.webp": require("../../packs/solar-system/images/venus.thumb.webp"),
      "images/earth.webp": require("../../packs/solar-system/images/earth.webp"),
      "images/earth.thumb.webp": require("../../packs/solar-system/images/earth.thumb.webp"),
      "images/mars.webp": require("../../packs/solar-system/images/mars.webp"),
      "images/mars.thumb.webp": require("../../packs/solar-system/images/mars.thumb.webp"),
      "images/asteroid-belt.webp": require("../../packs/solar-system/images/asteroid-belt.webp"),
      "images/asteroid-belt.thumb.webp": require("../../packs/solar-system/images/asteroid-belt.thumb.webp"),
      "images/jupiter.webp": require("../../packs/solar-system/images/jupiter.webp"),
      "images/jupiter.thumb.webp": require("../../packs/solar-system/images/jupiter.thumb.webp"),
      "images/saturn.webp": require("../../packs/solar-system/images/saturn.webp"),
      "images/saturn.thumb.webp": require("../../packs/solar-system/images/saturn.thumb.webp"),
      "images/uranus.webp": require("../../packs/solar-system/images/uranus.webp"),
      "images/uranus.thumb.webp": require("../../packs/solar-system/images/uranus.thumb.webp"),
      "images/neptune.webp": require("../../packs/solar-system/images/neptune.webp"),
      "images/neptune.thumb.webp": require("../../packs/solar-system/images/neptune.thumb.webp"),
      "images/pluto.webp": require("../../packs/solar-system/images/pluto.webp"),
      "images/pluto.thumb.webp": require("../../packs/solar-system/images/pluto.thumb.webp"),
    },
  },
};
