/**
 * Media pipeline (workplan Stage 2a).
 *
 *   npm run media
 *
 * For every pack, for every entry in its `media` table:
 *   1. If no source image exists in packs/<id>/source/, generate a labelled
 *      placeholder there and mark the entry's attribution as PLACEHOLDER.
 *   2. Produce `ref` (WebP, fitted inside MAIN_SIZE) and `thumbnailRef`
 *      (WebP, cropped to THUMB_SIZE square) from the source.
 *   3. Write width, height and bytes back into pack.json.
 *
 * Authoring never involves exporting images by hand: drop an original into
 * source/ with the same base name as its ref, and re-run.
 */

import { mkdirSync, statSync } from "node:fs";
import { dirname, join, basename, extname } from "node:path";
import sharp from "sharp";

import type { AuthoredContentPack, AuthoredMediaAsset } from "../src/content";
import {
  findSource,
  listPackDirs,
  PLACEHOLDER_ATTRIBUTION,
  readPack,
  sourceDir,
  writePack,
} from "./lib/packs";

/** Longest edge of a milestone image. Phone resolution. */
export const MAIN_SIZE = 1080;
/** Square thumbnail edge. */
export const THUMB_SIZE = 320;
const MAIN_QUALITY = 80;
const THUMB_QUALITY = 70;

/** A stable hue per name, so each placeholder gets its own colour. */
export function hueFor(name: string): number {
  let h = 0;
  for (const ch of name) h = (h * 31 + ch.charCodeAt(0)) % 360;
  return h;
}

function escapeXml(text: string): string {
  return text.replace(/[<>&"']/g, (c) => `&#${c.charCodeAt(0)};`);
}

/** SVG for a placeholder: a coloured disc with the label beneath it. */
export function placeholderSvg(label: string, key: string): string {
  const hue = hueFor(key);
  const w = 1200;
  const h = 900;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
  <defs>
    <radialGradient id="bg" cx="50%" cy="40%" r="75%">
      <stop offset="0%" stop-color="hsl(${hue},30%,16%)"/>
      <stop offset="100%" stop-color="#0B1020"/>
    </radialGradient>
    <radialGradient id="disc" cx="38%" cy="35%" r="70%">
      <stop offset="0%" stop-color="hsl(${hue},75%,72%)"/>
      <stop offset="100%" stop-color="hsl(${hue},60%,30%)"/>
    </radialGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="url(#bg)"/>
  <circle cx="${w / 2}" cy="380" r="230" fill="url(#disc)"/>
  <text x="${w / 2}" y="740" text-anchor="middle" font-family="Segoe UI, Arial, sans-serif"
        font-size="72" font-weight="700" fill="#F2F4FA">${escapeXml(label)}</text>
  <text x="${w / 2}" y="810" text-anchor="middle" font-family="Segoe UI, Arial, sans-serif"
        font-size="32" fill="#9AA3C0">placeholder image</text>
</svg>`;
}

/** The label for a media entry: the milestone title that uses it, else the pack title. */
function labelFor(pack: AuthoredContentPack, asset: AuthoredMediaAsset): string {
  const milestone = pack.milestones.find((m) => m.mediaRefs.includes(asset.ref));
  return milestone?.title ?? pack.title;
}

async function processPack(packDir: string): Promise<void> {
  const pack = readPack(packDir);
  mkdirSync(sourceDir(packDir), { recursive: true });

  for (const asset of pack.media) {
    if (asset.type !== "image") continue;

    let source = findSource(packDir, asset.ref);
    if (source === null) {
      const stem = basename(asset.ref, extname(asset.ref));
      source = join(sourceDir(packDir), `${stem}.png`);
      await sharp(Buffer.from(placeholderSvg(labelFor(pack, asset), stem)))
        .png()
        .toFile(source);
      asset.attribution = `${PLACEHOLDER_ATTRIBUTION} — generated by scripts/media.ts; replace before release.`;
      console.log(`  placeholder  ${asset.ref}`);
    }

    const mainPath = join(packDir, asset.ref);
    mkdirSync(dirname(mainPath), { recursive: true });
    const info = await sharp(source)
      .rotate()
      .resize(MAIN_SIZE, MAIN_SIZE, { fit: "inside", withoutEnlargement: true })
      .webp({ quality: MAIN_QUALITY })
      .toFile(mainPath);

    if (asset.thumbnailRef !== undefined) {
      const thumbPath = join(packDir, asset.thumbnailRef);
      mkdirSync(dirname(thumbPath), { recursive: true });
      await sharp(source)
        .rotate()
        .resize(THUMB_SIZE, THUMB_SIZE, { fit: "cover" })
        .webp({ quality: THUMB_QUALITY })
        .toFile(thumbPath);
    }

    asset.width = info.width;
    asset.height = info.height;
    asset.bytes = statSync(mainPath).size;
    console.log(`  ${asset.ref}  ${info.width}×${info.height}  ${asset.bytes} B`);
  }

  writePack(packDir, pack);
}

async function main(): Promise<void> {
  for (const packDir of listPackDirs()) {
    console.log(`${basename(packDir)}:`);
    await processPack(packDir);
  }
}

if (process.argv[1] !== undefined && import.meta.url.endsWith(basename(process.argv[1]))) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
